columnSuffix: null
contentColumnType: string
fieldGroup: 3195fae9-4da7-4239-b870-0ba0c2740f04 # Common
handle: contentBlocks
instructions: null
name: 'Content Blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentblocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
