currLabel: Einträge
customIcon: null
enabled: true
handle: entries
icon: section
layout: df7a4b78-bb14-4674-9f8a-b5b746984c2e # Default
level: 1
newWindow: false
parent: null
prevLabel: Einträge
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 2
subnavBehaviour: null
type: craft
url: entries
