currLabel: Einstellungen
customIcon: null
enabled: true
handle: settings
icon: settings
layout: df7a4b78-bb14-4674-9f8a-b5b746984c2e # Default
level: 1
newWindow: false
parent: null
prevLabel: Einstellungen
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 5
subnavBehaviour: null
type: craft
url: settings
