currLabel: Werkzeuge
customIcon: null
enabled: true
handle: utilities
icon: tool
layout: df7a4b78-bb14-4674-9f8a-b5b746984c2e # Default
level: 1
newWindow: false
parent: null
prevLabel: Werkzeuge
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 4
subnavBehaviour: null
type: craft
url: utilities
